import { AgentRunState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const AGENT_RUN_MATRIX: StateMatrix<AgentRunState> = [
  {
    fromState: AgentRunState.QUEUED,
    toState: AgentRunState.RUNNING,
    triggeringCommand: 'StartAgentRunCommand',
    actor: 'system',
    guardDescription: 'execution slot available; workflow lock acquired',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['agent_run.started'],
    idempotencyKeyTemplate: 'start-agent-run:{agentRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AgentRunState.RUNNING,
    toState: AgentRunState.SUCCEEDED,
    triggeringCommand: 'RecordAgentRunSucceededCommand',
    actor: 'system',
    guardDescription: 'adapter completed successfully; output validated',
    sideEffects: [
      'store_adapter_output',
      'release_workflow_lock',
      'write_workflow_event',
      'write_outbox_event',
    ],
    emittedEvents: ['agent_run.succeeded'],
    idempotencyKeyTemplate: 'agent-run-succeeded:{agentRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AgentRunState.RUNNING,
    toState: AgentRunState.FAILED,
    triggeringCommand: 'RecordAgentRunFailedCommand',
    actor: 'system',
    guardDescription: 'adapter failed beyond retry threshold',
    sideEffects: [
      'record_agent_error',
      'release_workflow_lock',
      'write_workflow_event',
      'write_outbox_event',
    ],
    emittedEvents: ['agent_run.failed'],
    idempotencyKeyTemplate: 'agent-run-failed:{agentRunId}',
    recoveryPath: 'Feature transitions to system_failed or failed depending on error type',
  },
  {
    fromState: AgentRunState.RUNNING,
    toState: AgentRunState.CANCELLED,
    triggeringCommand: 'CancelAgentRunCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator cancels in-flight run',
    sideEffects: ['release_workflow_lock', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['agent_run.cancelled'],
    idempotencyKeyTemplate: 'cancel-agent-run:{agentRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AgentRunState.QUEUED,
    toState: AgentRunState.CANCELLED,
    triggeringCommand: 'CancelAgentRunCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator cancels queued run before it starts',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['agent_run.cancelled'],
    idempotencyKeyTemplate: 'cancel-queued-agent-run:{agentRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
