import { ArtifactExportState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const ARTIFACT_EXPORT_MATRIX: StateMatrix<ArtifactExportState> = [
  {
    fromState: ArtifactExportState.PENDING,
    toState: ArtifactExportState.GENERATING,
    triggeringCommand: 'StartArtifactGenerationCommand',
    actor: 'system',
    guardDescription: 'generation task picked up by DocumentationAgentAdapter or export task',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.generating'],
    idempotencyKeyTemplate: 'start-artifact-generation:{artifactExportId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ArtifactExportState.GENERATING,
    toState: ArtifactExportState.EXPORTED,
    triggeringCommand: 'RecordArtifactExportedCommand',
    actor: 'system',
    guardDescription: 'artifact generation succeeded; content stored',
    sideEffects: ['store_artifact_content', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.exported'],
    idempotencyKeyTemplate: 'artifact-exported:{artifactExportId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ArtifactExportState.GENERATING,
    toState: ArtifactExportState.FAILED,
    triggeringCommand: 'RecordArtifactExportFailedCommand',
    actor: 'system',
    guardDescription: 'generation failed beyond retry threshold',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.failed'],
    idempotencyKeyTemplate: 'artifact-export-failed:{artifactExportId}',
    recoveryPath: 'Operator may re-trigger generation',
  },
  {
    fromState: ArtifactExportState.EXPORTED,
    toState: ArtifactExportState.STALE,
    triggeringCommand: 'MarkArtifactStaleCommand',
    actor: 'system',
    guardDescription: 'underlying plan or backlog has changed since export',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.stale'],
    idempotencyKeyTemplate: 'artifact-stale:{artifactExportId}',
    recoveryPath: 'Operator re-exports to get a fresh artifact',
  },
  {
    fromState: ArtifactExportState.STALE,
    toState: ArtifactExportState.GENERATING,
    triggeringCommand: 'StartArtifactGenerationCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator re-triggers export of stale artifact',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.generating'],
    idempotencyKeyTemplate: 'restart-artifact-generation:{artifactExportId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ArtifactExportState.FAILED,
    toState: ArtifactExportState.GENERATING,
    triggeringCommand: 'StartArtifactGenerationCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator re-triggers export after failure',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['artifact_export.generating'],
    idempotencyKeyTemplate: 'retry-artifact-generation:{artifactExportId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
