import { AutomationState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const AUTOMATION_CONTROL_MATRIX: StateMatrix<AutomationState> = [
  {
    fromState: AutomationState.RUNNING,
    toState: AutomationState.PAUSED_BY_OPERATOR,
    triggeringCommand: 'PauseAutomationCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator-initiated pause',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.paused_by_operator'],
    idempotencyKeyTemplate: 'pause-automation:{projectId}',
    recoveryPath: 'Idempotent: already paused returns cached result',
  },
  {
    fromState: AutomationState.PAUSED_BY_OPERATOR,
    toState: AutomationState.RUNNING,
    triggeringCommand: 'ResumeAutomationCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator resumes; records resumed event',
    sideEffects: ['record_policy_decision', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.resumed'],
    idempotencyKeyTemplate: 'resume-automation:{projectId}',
    recoveryPath: 'Idempotent: already running returns cached result',
  },
  {
    fromState: AutomationState.RUNNING,
    toState: AutomationState.PAUSED_BUDGET_EXCEEDED,
    triggeringCommand: 'RecordBudgetExceededCommand',
    actor: 'system',
    guardDescription: 'hard budget limit breached',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.budget_exceeded'],
    idempotencyKeyTemplate: 'budget-exceeded:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AutomationState.PAUSED_BUDGET_EXCEEDED,
    toState: AutomationState.RUNNING,
    triggeringCommand: 'ApproveBudgetOverrideCommand',
    actor: UserRole.APPROVER,
    guardDescription: 'approver overrides budget and resumes',
    sideEffects: ['record_policy_decision', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.budget_override_approved', 'automation.resumed'],
    idempotencyKeyTemplate: 'budget-override:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AutomationState.RUNNING,
    toState: AutomationState.WAITING_FOR_BUDGET_APPROVAL,
    triggeringCommand: 'RecordBudgetApprovalWaitingCommand',
    actor: 'system',
    guardDescription: 'soft budget limit breached; awaiting approver override',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.budget_approval_waiting'],
    idempotencyKeyTemplate: 'budget-approval-waiting:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: AutomationState.WAITING_FOR_BUDGET_APPROVAL,
    toState: AutomationState.RUNNING,
    triggeringCommand: 'ApproveBudgetOverrideCommand',
    actor: UserRole.APPROVER,
    guardDescription: 'approver approves budget override',
    sideEffects: ['record_policy_decision', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['automation.budget_override_approved', 'automation.resumed'],
    idempotencyKeyTemplate: 'budget-override-waiting:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
