import { FeatureExecutionState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const FEATURE_EXECUTION_MATRIX: StateMatrix<FeatureExecutionState> = [
  // ── Main flow ──────────────────────────────────────────────────────────────
  {
    fromState: FeatureExecutionState.APPROVED_PENDING_EXECUTION,
    toState: FeatureExecutionState.SELECTED,
    triggeringCommand: 'SelectFeatureCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'automationState=running; no other active feature run for project; all feature dependencies merged',
    sideEffects: ['set_active_feature_run', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.selected'],
    idempotencyKeyTemplate: 'select-feature:{featureRunId}',
    recoveryPath: 'Lock expires; reconciliation clears active_feature_run_id; feature returns to approved_pending_execution',
  },
  {
    fromState: FeatureExecutionState.SELECTED,
    toState: FeatureExecutionState.CODING,
    triggeringCommand: 'StartCodingCommand',
    actor: 'system',
    guardDescription: 'workflow lock held with valid fence; feature run id matches active_feature_run_id',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.coding_started'],
    idempotencyKeyTemplate: 'start-coding:{featureRunId}',
    recoveryPath: 'Idempotent replay returns cached result; lock prevents concurrent start',
  },
  {
    fromState: FeatureExecutionState.CODING,
    toState: FeatureExecutionState.CODE_PUSHED,
    triggeringCommand: 'RecordCodePushedCommand',
    actor: 'system',
    guardDescription: 'workflow lock held with valid fence; commit sha provided',
    sideEffects: ['record_commit_sha', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.code_pushed'],
    idempotencyKeyTemplate: 'record-code-pushed:{featureRunId}:{commitSha}',
    recoveryPath: 'Idempotent: same commitSha returns cached result',
  },
  {
    fromState: FeatureExecutionState.CODE_PUSHED,
    toState: FeatureExecutionState.PR_OPENED,
    triggeringCommand: 'RecordPrOpenedCommand',
    actor: 'system',
    guardDescription: 'workflow lock held; pull request number provided',
    sideEffects: ['record_pr_number', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.pr_opened'],
    idempotencyKeyTemplate: 'record-pr-opened:{featureRunId}:{prNumber}',
    recoveryPath: 'Idempotent: same prNumber returns cached result',
  },
  {
    fromState: FeatureExecutionState.PR_OPENED,
    toState: FeatureExecutionState.CI_RUNNING,
    triggeringCommand: 'RecordCiRunningCommand',
    actor: 'system',
    guardDescription: 'workflow lock held; CI check run id provided',
    sideEffects: ['record_ci_run_id', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.ci_running'],
    idempotencyKeyTemplate: 'record-ci-running:{featureRunId}:{checkRunId}',
    recoveryPath: 'Idempotent: same checkRunId returns cached result',
  },
  // ── CI outcomes ───────────────────────────────────────────────────────────
  {
    fromState: FeatureExecutionState.CI_RUNNING,
    toState: FeatureExecutionState.UNDER_REVIEW,
    triggeringCommand: 'RecordCiPassedCommand',
    actor: 'system',
    guardDescription: 'CI check run concluded with success status',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.ci_passed'],
    idempotencyKeyTemplate: 'record-ci-passed:{featureRunId}:{checkRunId}',
    recoveryPath: 'Idempotent: same checkRunId returns cached result',
  },
  {
    fromState: FeatureExecutionState.CI_RUNNING,
    toState: FeatureExecutionState.CI_FAILED,
    triggeringCommand: 'RecordCiFailedCommand',
    actor: 'system',
    guardDescription: 'CI check run concluded with failure status',
    sideEffects: ['record_blocking_finding', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.ci_failed'],
    idempotencyKeyTemplate: 'record-ci-failed:{featureRunId}:{checkRunId}',
    recoveryPath: 'Idempotent: same checkRunId returns cached result',
  },
  {
    fromState: FeatureExecutionState.CI_FAILED,
    toState: FeatureExecutionState.CHANGES_REQUESTED,
    triggeringCommand: 'RequestChangesAfterCiFailCommand',
    actor: 'system',
    guardDescription: 'fix-attempt count < per-feature threshold',
    sideEffects: ['increment_fix_attempt_count', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.changes_requested'],
    idempotencyKeyTemplate: 'changes-requested-after-ci:{featureRunId}',
    recoveryPath: 'Idempotent: returns cached result if already transitioned',
  },
  {
    fromState: FeatureExecutionState.CI_FAILED,
    toState: FeatureExecutionState.HUMAN_REQUIRED,
    triggeringCommand: 'EscalateToHumanCommand',
    actor: 'system',
    guardDescription: 'fix-attempt count >= per-feature threshold (review-cycle limit exceeded)',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.human_required'],
    idempotencyKeyTemplate: 'escalate-human-ci-limit:{featureRunId}',
    recoveryPath: 'Human resolves via human_required disposition',
  },
  // ── Review loop ───────────────────────────────────────────────────────────
  {
    fromState: FeatureExecutionState.UNDER_REVIEW,
    toState: FeatureExecutionState.CHANGES_REQUESTED,
    triggeringCommand: 'RecordChangesRequestedCommand',
    actor: 'system',
    guardDescription: 'reviewer produced blocking findings; fix-attempt count < threshold',
    sideEffects: ['increment_fix_attempt_count', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.changes_requested'],
    idempotencyKeyTemplate: 'changes-requested:{featureRunId}:{reviewId}',
    recoveryPath: 'Idempotent: same reviewId returns cached result',
  },
  {
    fromState: FeatureExecutionState.UNDER_REVIEW,
    toState: FeatureExecutionState.HUMAN_REQUIRED,
    triggeringCommand: 'EscalateToHumanCommand',
    actor: 'system',
    guardDescription: 'requires_human_decision finding present, or fix-attempt limit exceeded',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.human_required'],
    idempotencyKeyTemplate: 'escalate-human-review:{featureRunId}',
    recoveryPath: 'Human resolves via human_required disposition',
  },
  {
    fromState: FeatureExecutionState.UNDER_REVIEW,
    toState: FeatureExecutionState.APPROVED_BY_POLICY,
    triggeringCommand: 'RecordApprovedByPolicyCommand',
    actor: 'system',
    guardDescription: 'merge gate passes: no blocking findings, CI green, required approvals met',
    sideEffects: ['write_merge_gate_evaluation', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.approved_by_policy'],
    idempotencyKeyTemplate: 'approved-by-policy:{featureRunId}',
    recoveryPath: 'Idempotent: returns cached result if already approved',
  },
  {
    fromState: FeatureExecutionState.CHANGES_REQUESTED,
    toState: FeatureExecutionState.FIXING,
    triggeringCommand: 'StartFixingCommand',
    actor: 'system',
    guardDescription: 'workflow lock held with valid fence',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.fixing_started'],
    idempotencyKeyTemplate: 'start-fixing:{featureRunId}',
    recoveryPath: 'Idempotent replay returns cached result',
  },
  {
    fromState: FeatureExecutionState.FIXING,
    toState: FeatureExecutionState.CODE_PUSHED,
    triggeringCommand: 'RecordCodePushedCommand',
    actor: 'system',
    guardDescription: 'workflow lock held with valid fence; commit sha provided',
    sideEffects: ['record_commit_sha', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.code_pushed'],
    idempotencyKeyTemplate: 'record-code-pushed:{featureRunId}:{commitSha}',
    recoveryPath: 'Idempotent: same commitSha returns cached result',
  },
  // ── Merge path ────────────────────────────────────────────────────────────
  {
    fromState: FeatureExecutionState.APPROVED_BY_POLICY,
    toState: FeatureExecutionState.MERGE_READY,
    triggeringCommand: 'MergeIfReadyCommand',
    actor: UserRole.APPROVER,
    guardDescription: 'merge gate re-evaluated immediately; all conditions still met',
    sideEffects: ['write_merge_gate_evaluation', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.merge_ready'],
    idempotencyKeyTemplate: 'merge-ready:{featureRunId}',
    recoveryPath: 'Idempotent: returns cached result if already merge_ready',
  },
  {
    fromState: FeatureExecutionState.MERGE_READY,
    toState: FeatureExecutionState.MERGED,
    triggeringCommand: 'RecordMergedCommand',
    actor: 'system',
    guardDescription: 'GitHub merge confirmed; merge commit sha provided',
    sideEffects: ['clear_active_feature_run', 'record_merge_sha', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.merged'],
    idempotencyKeyTemplate: 'record-merged:{featureRunId}:{mergeSha}',
    recoveryPath: 'Idempotent: same mergeSha returns cached result',
  },
  {
    fromState: FeatureExecutionState.MERGE_READY,
    toState: FeatureExecutionState.MERGE_FAILED,
    triggeringCommand: 'RecordMergeFailedCommand',
    actor: 'system',
    guardDescription: 'GitHub merge attempt rejected after merge_ready',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.merge_failed'],
    idempotencyKeyTemplate: 'record-merge-failed:{featureRunId}',
    recoveryPath: 'Reconciliation re-checks; routes to under_review or human_required',
  },
  {
    fromState: FeatureExecutionState.MERGE_FAILED,
    toState: FeatureExecutionState.UNDER_REVIEW,
    triggeringCommand: 'ReconcileMergeFailedCommand',
    actor: 'system',
    guardDescription: 'merge failure is auto-clearable (e.g. stale SHA; re-push resolves it)',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.returned_to_review'],
    idempotencyKeyTemplate: 'reconcile-merge-failed:{featureRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: FeatureExecutionState.MERGE_FAILED,
    toState: FeatureExecutionState.HUMAN_REQUIRED,
    triggeringCommand: 'EscalateToHumanCommand',
    actor: 'system',
    guardDescription: 'merge failure cannot be auto-cleared (branch protection, conflict)',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.human_required'],
    idempotencyKeyTemplate: 'escalate-human-merge-failed:{featureRunId}',
    recoveryPath: 'Human resolves via human_required disposition',
  },
  // ── Failure / escalation states ───────────────────────────────────────────
  {
    fromState: FeatureExecutionState.FAILED,
    toState: FeatureExecutionState.HUMAN_REQUIRED,
    triggeringCommand: 'EscalateToHumanCommand',
    actor: 'system',
    guardDescription: 'operation exhausted retries; requires human disposition',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.human_required'],
    idempotencyKeyTemplate: 'escalate-human-failed:{featureRunId}',
    recoveryPath: 'Human dispositions: retry, skip, or block',
  },
  {
    fromState: FeatureExecutionState.SYSTEM_FAILED,
    toState: FeatureExecutionState.HUMAN_REQUIRED,
    triggeringCommand: 'EscalateToHumanCommand',
    actor: 'system',
    guardDescription: 'infrastructure/sandbox/timeout failure beyond retry thresholds; locks already released',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.human_required'],
    idempotencyKeyTemplate: 'escalate-human-system-failed:{featureRunId}',
    recoveryPath: 'Human reviews system diagnostics and retries or skips',
  },
  {
    fromState: FeatureExecutionState.BLOCKED,
    toState: FeatureExecutionState.APPROVED_PENDING_EXECUTION,
    triggeringCommand: 'UnblockFeatureCommand',
    actor: 'system',
    guardDescription: 'all blocking dependencies now merged; precondition satisfied',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['feature.unblocked'],
    idempotencyKeyTemplate: 'unblock-feature:{featureRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
