import { ProjectState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const PROJECT_LIFECYCLE_MATRIX: StateMatrix<ProjectState> = [
  {
    fromState: ProjectState.ACTIVE,
    toState: ProjectState.IMPLEMENTATION_COMPLETE,
    triggeringCommand: 'MarkImplementationCompleteCommand',
    actor: 'system',
    guardDescription: 'all approved feature requests in merged state; Project Acceptance Validation passes (01-system-specification.md §13.1)',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.implementation_complete'],
    idempotencyKeyTemplate: 'implementation-complete:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ProjectState.IMPLEMENTATION_COMPLETE,
    toState: ProjectState.DESIGN_DOCUMENT_GENERATING,
    triggeringCommand: 'GenerateDesignDocumentCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'implementation_complete state confirmed',
    sideEffects: ['create_artifact_export_record', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.design_document_generating'],
    idempotencyKeyTemplate: 'generate-design-doc:{projectId}',
    recoveryPath: 'Idempotent: returns cached result if already generating',
  },
  {
    fromState: ProjectState.DESIGN_DOCUMENT_GENERATING,
    toState: ProjectState.DESIGN_DOCUMENT_READY_FOR_REVIEW,
    triggeringCommand: 'RecordDesignDocumentReadyCommand',
    actor: 'system',
    guardDescription: 'DocumentationAgentAdapter completed generation; artifact exported',
    sideEffects: ['mark_artifact_exported', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.design_document_ready'],
    idempotencyKeyTemplate: 'design-doc-ready:{projectId}:{artifactId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ProjectState.DESIGN_DOCUMENT_READY_FOR_REVIEW,
    toState: ProjectState.DESIGN_DOCUMENT_REVISION_REQUESTED,
    triggeringCommand: 'RequestDesignDocumentRevisionCommand',
    actor: UserRole.APPROVER,
    guardDescription: 'approver has reviewed and requests changes',
    sideEffects: ['record_human_approval', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.design_document_revision_requested'],
    idempotencyKeyTemplate: 'request-design-revision:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ProjectState.DESIGN_DOCUMENT_REVISION_REQUESTED,
    toState: ProjectState.DESIGN_DOCUMENT_GENERATING,
    triggeringCommand: 'RegenerateDesignDocumentCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'revision_requested state confirmed',
    sideEffects: ['create_artifact_export_record', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.design_document_regenerating'],
    idempotencyKeyTemplate: 'regenerate-design-doc:{projectId}',
    recoveryPath: 'Idempotent: returns cached result if already generating',
  },
  {
    fromState: ProjectState.DESIGN_DOCUMENT_READY_FOR_REVIEW,
    toState: ProjectState.DESIGN_DOCUMENT_APPROVED,
    triggeringCommand: 'ApproveDesignDocumentCommand',
    actor: UserRole.APPROVER,
    guardDescription: 'approver reviews and approves the final design document',
    sideEffects: ['record_human_approval', 'write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.design_document_approved'],
    idempotencyKeyTemplate: 'approve-design-doc:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: ProjectState.DESIGN_DOCUMENT_APPROVED,
    toState: ProjectState.PROJECT_COMPLETE,
    triggeringCommand: 'CompleteProjectCommand',
    actor: 'system',
    guardDescription: 'design document approved; all exit conditions met',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['project.complete'],
    idempotencyKeyTemplate: 'complete-project:{projectId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
