import { WorkflowRunState, UserRole } from '../../domain/states.js';
import type { StateMatrix } from '../types.js';

export const WORKFLOW_RUN_MATRIX: StateMatrix<WorkflowRunState> = [
  {
    fromState: WorkflowRunState.QUEUED,
    toState: WorkflowRunState.RUNNING,
    triggeringCommand: 'StartWorkflowRunCommand',
    actor: 'system',
    guardDescription: 'Trigger.dev task picked up by worker',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.started'],
    idempotencyKeyTemplate: 'start-workflow-run:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.RUNNING,
    toState: WorkflowRunState.WAITING,
    triggeringCommand: 'RecordWorkflowWaitingCommand',
    actor: 'system',
    guardDescription: 'workflow task is waiting on an external event (e.g. webhook, approval)',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.waiting'],
    idempotencyKeyTemplate: 'workflow-waiting:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.WAITING,
    toState: WorkflowRunState.RUNNING,
    triggeringCommand: 'ResumeWorkflowRunCommand',
    actor: 'system',
    guardDescription: 'awaited event received or condition met',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.resumed'],
    idempotencyKeyTemplate: 'resume-workflow-run:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.RUNNING,
    toState: WorkflowRunState.SUCCEEDED,
    triggeringCommand: 'RecordWorkflowSucceededCommand',
    actor: 'system',
    guardDescription: 'workflow task completed successfully',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.succeeded'],
    idempotencyKeyTemplate: 'workflow-succeeded:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.RUNNING,
    toState: WorkflowRunState.FAILED,
    triggeringCommand: 'RecordWorkflowFailedCommand',
    actor: 'system',
    guardDescription: 'workflow task failed beyond retry threshold',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.failed'],
    idempotencyKeyTemplate: 'workflow-failed:{workflowRunId}',
    recoveryPath: 'Feature transitions to system_failed',
  },
  {
    fromState: WorkflowRunState.RUNNING,
    toState: WorkflowRunState.CANCELLED,
    triggeringCommand: 'CancelWorkflowRunCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator cancels in-flight workflow',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.cancelled'],
    idempotencyKeyTemplate: 'cancel-workflow-run:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.WAITING,
    toState: WorkflowRunState.CANCELLED,
    triggeringCommand: 'CancelWorkflowRunCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator cancels waiting workflow',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.cancelled'],
    idempotencyKeyTemplate: 'cancel-waiting-workflow-run:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
  {
    fromState: WorkflowRunState.QUEUED,
    toState: WorkflowRunState.CANCELLED,
    triggeringCommand: 'CancelWorkflowRunCommand',
    actor: UserRole.OPERATOR,
    guardDescription: 'operator cancels queued workflow before it starts',
    sideEffects: ['write_workflow_event', 'write_outbox_event'],
    emittedEvents: ['workflow_run.cancelled'],
    idempotencyKeyTemplate: 'cancel-queued-workflow-run:{workflowRunId}',
    recoveryPath: 'Idempotent: returns cached result',
  },
] as const;
