import { getApiClient } from '../../lib/api-server';
import { resolveProjectId } from '../../lib/project';
import { ProjectSwitcher } from '../../components/project-switcher';
import { StatusBadge } from '../../components/status-badge';
import { Table } from '../../components/table';

export default async function ArtifactsPage({
  searchParams,
}: {
  searchParams: Promise<{ project?: string }>;
}): Promise<JSX.Element> {
  const client = getApiClient();
  const projectId = await resolveProjectId(searchParams);
  const [projects, artifacts] = await Promise.all([
    client.listProjects({ limit: '100' }),
    client.listArtifactExports(projectId, { limit: '50' }),
  ]);

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1>Artifacts</h1>
        <ProjectSwitcher projects={projects.items} currentProjectId={projectId} />
      </div>
      <p style={{ color: '#64748b' }}>
        Artifact exports are generated snapshots (`plan.md`, `backlog.md`, etc.) — never live state.
        Generated by backlog/plan export commands; not created directly from this page.
      </p>
      <Table
        rows={artifacts.items}
        rowKey={(row) => row.id}
        columns={[
          { key: 'type', header: 'Type', render: (row) => row.artifact_type },
          { key: 'state', header: 'State', render: (row) => <StatusBadge value={row.state} /> },
          { key: 'format', header: 'Format', render: (row) => row.format },
          { key: 'exported', header: 'Exported at', render: (row) => row.exported_at ?? '—' },
          { key: 'error', header: 'Error', render: (row) => row.error ?? '—' },
        ]}
      />
    </div>
  );
}
