-- Migration: 0001_initial_schema
-- Dialect: SQLite
-- All timestamps stored as ISO-8601 TEXT in UTC.
-- Booleans stored as INTEGER (0=false, 1=true).
-- JSON stored as TEXT.
-- UUIDs generated by the application and stored as TEXT.

PRAGMA foreign_keys = ON;

-- ============================================================
-- Projects & Repositories
-- ============================================================

CREATE TABLE projects (
  id          TEXT    PRIMARY KEY,
  name        TEXT    NOT NULL,
  description TEXT,
  state       TEXT    NOT NULL DEFAULT 'active',
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_projects_state ON projects(state);

CREATE TABLE repositories (
  id             TEXT    PRIMARY KEY,
  project_id     TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  owner          TEXT    NOT NULL,
  name           TEXT    NOT NULL,
  full_name      TEXT    NOT NULL,
  default_branch TEXT    NOT NULL DEFAULT 'main',
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_repositories_project_id ON repositories(project_id);

CREATE TABLE github_links (
  id              TEXT    PRIMARY KEY,
  project_id      TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  repository_id   TEXT    REFERENCES repositories(id),
  installation_id TEXT,
  app_id          TEXT,
  linked_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  version         INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_github_links_project_id ON github_links(project_id);

-- ============================================================
-- Specification & Planning
-- ============================================================

CREATE TABLE specification_inputs (
  id           TEXT    PRIMARY KEY,
  project_id   TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  content      TEXT    NOT NULL,
  content_type TEXT    NOT NULL DEFAULT 'text/plain',
  version      INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_specification_inputs_project_id ON specification_inputs(project_id);

CREATE TABLE planning_readiness_assessments (
  id                     TEXT    PRIMARY KEY,
  project_id             TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  specification_input_id TEXT    REFERENCES specification_inputs(id),
  status                 TEXT    NOT NULL,
  summary                TEXT,
  version                INTEGER NOT NULL DEFAULT 1,
  created_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_readiness_assessments_project_id ON planning_readiness_assessments(project_id);

CREATE TABLE planning_gaps (
  id            TEXT    PRIMARY KEY,
  assessment_id TEXT    NOT NULL REFERENCES planning_readiness_assessments(id) ON DELETE CASCADE,
  description   TEXT    NOT NULL,
  severity      TEXT    NOT NULL,
  resolution    TEXT,
  resolved_at   TEXT,
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_planning_gaps_assessment_id ON planning_gaps(assessment_id);

CREATE TABLE planning_questions (
  id            TEXT    PRIMARY KEY,
  assessment_id TEXT    NOT NULL REFERENCES planning_readiness_assessments(id) ON DELETE CASCADE,
  question      TEXT    NOT NULL,
  answer        TEXT,
  answered_at   TEXT,
  round         INTEGER NOT NULL DEFAULT 1,
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_planning_questions_assessment_id ON planning_questions(assessment_id);

CREATE TABLE planning_assumptions (
  id            TEXT    PRIMARY KEY,
  assessment_id TEXT    NOT NULL REFERENCES planning_readiness_assessments(id) ON DELETE CASCADE,
  description   TEXT    NOT NULL,
  confidence    TEXT    NOT NULL DEFAULT 'medium',
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_planning_assumptions_assessment_id ON planning_assumptions(assessment_id);

-- ============================================================
-- Implementation Plans & Feature Requests
-- ============================================================

CREATE TABLE implementation_plans (
  id            TEXT    PRIMARY KEY,
  project_id    TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  assessment_id TEXT    REFERENCES planning_readiness_assessments(id),
  state         TEXT    NOT NULL DEFAULT 'draft',
  title         TEXT    NOT NULL,
  summary       TEXT,
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_implementation_plans_project_id ON implementation_plans(project_id);
CREATE INDEX idx_implementation_plans_state ON implementation_plans(state);

CREATE TABLE plan_sections (
  id          TEXT    PRIMARY KEY,
  plan_id     TEXT    NOT NULL REFERENCES implementation_plans(id) ON DELETE CASCADE,
  title       TEXT    NOT NULL,
  content     TEXT    NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_plan_sections_plan_id ON plan_sections(plan_id);

CREATE TABLE feature_requests (
  id          TEXT    PRIMARY KEY,
  plan_id     TEXT    NOT NULL REFERENCES implementation_plans(id) ON DELETE CASCADE,
  project_id  TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  fr_id       TEXT    NOT NULL,
  title       TEXT    NOT NULL,
  description TEXT    NOT NULL,
  kind        TEXT    NOT NULL DEFAULT 'feature',
  executable  INTEGER NOT NULL DEFAULT 1,
  state       TEXT    NOT NULL DEFAULT 'approved_pending_execution',
  priority    INTEGER NOT NULL DEFAULT 0,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(project_id, fr_id)
);

CREATE INDEX idx_feature_requests_project_id ON feature_requests(project_id);
CREATE INDEX idx_feature_requests_state ON feature_requests(state);
CREATE INDEX idx_feature_requests_plan_id ON feature_requests(plan_id);

CREATE TABLE feature_dependencies (
  id           TEXT PRIMARY KEY,
  source_fr_id TEXT NOT NULL REFERENCES feature_requests(id) ON DELETE CASCADE,
  target_fr_id TEXT NOT NULL REFERENCES feature_requests(id) ON DELETE CASCADE,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(source_fr_id, target_fr_id)
);

CREATE INDEX idx_feature_deps_source ON feature_dependencies(source_fr_id);
CREATE INDEX idx_feature_deps_target ON feature_dependencies(target_fr_id);

CREATE TABLE acceptance_criteria (
  id                 TEXT    PRIMARY KEY,
  feature_request_id TEXT    NOT NULL REFERENCES feature_requests(id) ON DELETE CASCADE,
  description        TEXT    NOT NULL,
  order_index        INTEGER NOT NULL DEFAULT 0,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_acceptance_criteria_fr_id ON acceptance_criteria(feature_request_id);

CREATE TABLE test_expectations (
  id                 TEXT    PRIMARY KEY,
  feature_request_id TEXT    NOT NULL REFERENCES feature_requests(id) ON DELETE CASCADE,
  description        TEXT    NOT NULL,
  test_type          TEXT,
  order_index        INTEGER NOT NULL DEFAULT 0,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_test_expectations_fr_id ON test_expectations(feature_request_id);

-- ============================================================
-- Workflow Execution
-- ============================================================

CREATE TABLE workflow_states (
  id                    TEXT    PRIMARY KEY,
  project_id            TEXT    NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
  active_feature_run_id TEXT,
  automation_state      TEXT    NOT NULL DEFAULT 'running',
  version               INTEGER NOT NULL DEFAULT 1,
  created_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE feature_runs (
  id                       TEXT    PRIMARY KEY,
  feature_request_id       TEXT    NOT NULL REFERENCES feature_requests(id) ON DELETE CASCADE,
  attempt_no               INTEGER NOT NULL DEFAULT 1,
  current_execution_state  TEXT    NOT NULL DEFAULT 'approved_pending_execution',
  lock_id                  TEXT,
  started_at               TEXT,
  ended_at                 TEXT,
  outcome                  TEXT,
  version                  INTEGER NOT NULL DEFAULT 1,
  created_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_feature_runs_fr_id ON feature_runs(feature_request_id);
CREATE INDEX idx_feature_runs_state ON feature_runs(current_execution_state);

CREATE TABLE workflow_events (
  id                    TEXT NOT NULL PRIMARY KEY,
  feature_run_id        TEXT REFERENCES feature_runs(id),
  project_id            TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  event_type            TEXT NOT NULL,
  from_state            TEXT,
  to_state              TEXT,
  actor                 TEXT,
  payload               TEXT,
  payload_schema_version TEXT NOT NULL DEFAULT '1.0.0',
  occurred_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_workflow_events_project_id ON workflow_events(project_id);
CREATE INDEX idx_workflow_events_feature_run_id ON workflow_events(feature_run_id);
CREATE INDEX idx_workflow_events_occurred_at ON workflow_events(occurred_at);

CREATE TABLE workflow_locks (
  id           TEXT    PRIMARY KEY,
  project_id   TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  resource_key TEXT    NOT NULL,
  holder_id    TEXT    NOT NULL,
  fence        INTEGER NOT NULL,
  acquired_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  expires_at   TEXT,
  version      INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(project_id, resource_key)
);

-- ============================================================
-- Idempotency & Outbox/Inbox
-- ============================================================

CREATE TABLE idempotency_keys (
  id         TEXT PRIMARY KEY,
  key        TEXT NOT NULL,
  scope      TEXT NOT NULL DEFAULT 'global',
  result     TEXT,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(key, scope)
);

CREATE INDEX idx_idempotency_keys_expires_at ON idempotency_keys(expires_at);

CREATE TABLE outbox_events (
  id                     TEXT    PRIMARY KEY,
  event_type             TEXT    NOT NULL,
  payload                TEXT    NOT NULL,
  payload_schema_version TEXT    NOT NULL,
  status                 TEXT    NOT NULL DEFAULT 'pending',
  attempts               INTEGER NOT NULL DEFAULT 0,
  last_attempted_at      TEXT,
  delivered_at           TEXT,
  error                  TEXT,
  created_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_outbox_events_status ON outbox_events(status);
CREATE INDEX idx_outbox_events_created_at ON outbox_events(created_at);

CREATE TABLE inbox_events (
  id                     TEXT    PRIMARY KEY,
  dedup_key              TEXT    NOT NULL UNIQUE,
  source                 TEXT    NOT NULL DEFAULT 'github',
  event_type             TEXT    NOT NULL,
  payload                TEXT    NOT NULL,
  payload_schema_version TEXT    NOT NULL,
  status                 TEXT    NOT NULL DEFAULT 'pending',
  attempts               INTEGER NOT NULL DEFAULT 0,
  last_attempted_at      TEXT,
  processed_at           TEXT,
  error                  TEXT,
  created_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_inbox_events_status ON inbox_events(status);

-- ============================================================
-- Human Approvals & Policy Decisions
-- ============================================================

CREATE TABLE human_approvals (
  id                 TEXT    PRIMARY KEY,
  project_id         TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  feature_request_id TEXT    REFERENCES feature_requests(id),
  feature_run_id     TEXT    REFERENCES feature_runs(id),
  context_type       TEXT    NOT NULL,
  context_id         TEXT,
  decision           TEXT,
  actor              TEXT    NOT NULL,
  actor_role         TEXT    NOT NULL,
  notes              TEXT,
  decided_at         TEXT,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_human_approvals_project_id ON human_approvals(project_id);
CREATE INDEX idx_human_approvals_feature_run_id ON human_approvals(feature_run_id);

CREATE TABLE policy_decisions (
  id             TEXT    PRIMARY KEY,
  project_id     TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  feature_run_id TEXT    REFERENCES feature_runs(id),
  policy_type    TEXT    NOT NULL,
  decision       TEXT    NOT NULL,
  context        TEXT,
  actor          TEXT,
  decided_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_policy_decisions_project_id ON policy_decisions(project_id);

-- ============================================================
-- Agent Adapters & Runs
-- ============================================================

CREATE TABLE agent_adapters (
  id             TEXT    PRIMARY KEY,
  role           TEXT    NOT NULL,
  name           TEXT    NOT NULL,
  implementation TEXT    NOT NULL,
  is_active      INTEGER NOT NULL DEFAULT 1,
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE agent_capabilities (
  id         TEXT    PRIMARY KEY,
  adapter_id TEXT    NOT NULL REFERENCES agent_adapters(id) ON DELETE CASCADE,
  capability TEXT    NOT NULL,
  parameters TEXT,
  version    INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_agent_capabilities_adapter_id ON agent_capabilities(adapter_id);

CREATE TABLE agent_configurations (
  id         TEXT    PRIMARY KEY,
  adapter_id TEXT    NOT NULL REFERENCES agent_adapters(id) ON DELETE CASCADE,
  project_id TEXT    REFERENCES projects(id) ON DELETE CASCADE,
  config     TEXT    NOT NULL,
  version    INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_agent_configurations_adapter_id ON agent_configurations(adapter_id);

CREATE TABLE agent_runs (
  id             TEXT    PRIMARY KEY,
  adapter_id     TEXT    NOT NULL REFERENCES agent_adapters(id),
  project_id     TEXT    REFERENCES projects(id),
  feature_run_id TEXT    REFERENCES feature_runs(id),
  role           TEXT    NOT NULL,
  state          TEXT    NOT NULL DEFAULT 'queued',
  input_summary  TEXT,
  output_summary TEXT,
  error          TEXT,
  started_at     TEXT,
  ended_at       TEXT,
  tokens_used    INTEGER,
  cost_usd       REAL,
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_agent_runs_adapter_id ON agent_runs(adapter_id);
CREATE INDEX idx_agent_runs_feature_run_id ON agent_runs(feature_run_id);
CREATE INDEX idx_agent_runs_state ON agent_runs(state);

CREATE TABLE agent_errors (
  id           TEXT PRIMARY KEY,
  agent_run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  error_type   TEXT NOT NULL,
  message      TEXT NOT NULL,
  stack        TEXT,
  occurred_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_agent_errors_run_id ON agent_errors(agent_run_id);

CREATE TABLE agent_tool_operations (
  id             TEXT    PRIMARY KEY,
  agent_run_id   TEXT    NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  tool_name      TEXT    NOT NULL,
  input_summary  TEXT,
  output_summary TEXT,
  status         TEXT    NOT NULL DEFAULT 'success',
  duration_ms    INTEGER,
  occurred_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_agent_tool_ops_run_id ON agent_tool_operations(agent_run_id);

CREATE TABLE agent_context_packs (
  id                     TEXT    PRIMARY KEY,
  agent_run_id           TEXT    NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  content                TEXT    NOT NULL,
  content_schema_version TEXT    NOT NULL DEFAULT '1.0.0',
  version                INTEGER NOT NULL DEFAULT 1,
  created_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE adapter_conformance_results (
  id           TEXT    PRIMARY KEY,
  adapter_id   TEXT    REFERENCES agent_adapters(id),
  role         TEXT    NOT NULL,
  test_suite   TEXT    NOT NULL,
  passed       INTEGER NOT NULL DEFAULT 0,
  total_tests  INTEGER NOT NULL DEFAULT 0,
  failed_tests INTEGER NOT NULL DEFAULT 0,
  details      TEXT,
  run_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ============================================================
-- Review & Disagreement
-- ============================================================

CREATE TABLE review_findings (
  id                  TEXT    PRIMARY KEY,
  feature_run_id      TEXT    NOT NULL REFERENCES feature_runs(id) ON DELETE CASCADE,
  reviewer_run_id     TEXT    REFERENCES agent_runs(id),
  review_cycle        INTEGER NOT NULL DEFAULT 1,
  severity            TEXT    NOT NULL,
  category            TEXT,
  description         TEXT    NOT NULL,
  file_path           TEXT,
  line_start          INTEGER,
  line_end            INTEGER,
  resolved            INTEGER NOT NULL DEFAULT 0,
  resolved_by_run_id  TEXT    REFERENCES agent_runs(id),
  version             INTEGER NOT NULL DEFAULT 1,
  created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_review_findings_feature_run_id ON review_findings(feature_run_id);
CREATE INDEX idx_review_findings_severity ON review_findings(severity);

CREATE TABLE coder_responses (
  id            TEXT    PRIMARY KEY,
  finding_id    TEXT    NOT NULL REFERENCES review_findings(id) ON DELETE CASCADE,
  coder_run_id  TEXT    NOT NULL REFERENCES agent_runs(id),
  response_type TEXT    NOT NULL,
  notes         TEXT,
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_coder_responses_finding_id ON coder_responses(finding_id);

CREATE TABLE disagreement_records (
  id             TEXT    PRIMARY KEY,
  feature_run_id TEXT    NOT NULL REFERENCES feature_runs(id) ON DELETE CASCADE,
  finding_id     TEXT    REFERENCES review_findings(id),
  review_cycle   INTEGER NOT NULL,
  state          TEXT    NOT NULL DEFAULT 'open',
  arbiter_run_id TEXT    REFERENCES agent_runs(id),
  resolution     TEXT,
  resolved_at    TEXT,
  version        INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_disagreement_records_feature_run_id ON disagreement_records(feature_run_id);

-- ============================================================
-- Budget & Cost
-- ============================================================

CREATE TABLE budget_policies (
  id                 TEXT    PRIMARY KEY,
  project_id         TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  scope              TEXT    NOT NULL,
  feature_request_id TEXT    REFERENCES feature_requests(id),
  currency           TEXT    NOT NULL DEFAULT 'USD',
  soft_limit         REAL,
  hard_limit         REAL,
  window_days        INTEGER,
  is_active          INTEGER NOT NULL DEFAULT 1,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_budget_policies_project_id ON budget_policies(project_id);

CREATE TABLE cost_records (
  id                 TEXT    PRIMARY KEY,
  project_id         TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  feature_request_id TEXT    REFERENCES feature_requests(id),
  feature_run_id     TEXT    REFERENCES feature_runs(id),
  agent_run_id       TEXT    REFERENCES agent_runs(id),
  scope              TEXT    NOT NULL,
  amount             REAL    NOT NULL,
  currency           TEXT    NOT NULL DEFAULT 'USD',
  provider           TEXT,
  model              TEXT,
  input_tokens       INTEGER,
  output_tokens      INTEGER,
  recorded_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  expires_at         TEXT,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_cost_records_project_id ON cost_records(project_id);
CREATE INDEX idx_cost_records_expires_at ON cost_records(expires_at);

-- ============================================================
-- Artifacts & Design Documents
-- ============================================================

CREATE TABLE artifact_exports (
  id            TEXT    PRIMARY KEY,
  project_id    TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  artifact_type TEXT    NOT NULL,
  state         TEXT    NOT NULL DEFAULT 'pending',
  content       TEXT,
  format        TEXT    NOT NULL DEFAULT 'markdown',
  exported_at   TEXT,
  error         TEXT,
  version       INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_artifact_exports_project_id ON artifact_exports(project_id);

CREATE TABLE design_documents (
  id         TEXT    PRIMARY KEY,
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  state      TEXT    NOT NULL DEFAULT 'draft',
  version    INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_design_documents_project_id ON design_documents(project_id);

CREATE TABLE design_document_sections (
  id                 TEXT    PRIMARY KEY,
  design_document_id TEXT    NOT NULL REFERENCES design_documents(id) ON DELETE CASCADE,
  section_name       TEXT    NOT NULL,
  content            TEXT,
  order_index        INTEGER NOT NULL DEFAULT 0,
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(design_document_id, section_name)
);

CREATE TABLE design_decisions (
  id                 TEXT    PRIMARY KEY,
  project_id         TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  design_document_id TEXT    REFERENCES design_documents(id),
  title              TEXT    NOT NULL,
  context            TEXT,
  decision           TEXT    NOT NULL,
  consequences       TEXT,
  status             TEXT    NOT NULL DEFAULT 'accepted',
  version            INTEGER NOT NULL DEFAULT 1,
  created_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at         TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_design_decisions_project_id ON design_decisions(project_id);

CREATE TABLE glossary_terms (
  id         TEXT    PRIMARY KEY,
  project_id TEXT    REFERENCES projects(id) ON DELETE CASCADE,
  term       TEXT    NOT NULL,
  definition TEXT    NOT NULL,
  category   TEXT,
  version    INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  UNIQUE(term, project_id)
);

-- ============================================================
-- Trigger.dev & Merge Gate
-- ============================================================

CREATE TABLE triggerdev_runs (
  id                       TEXT    PRIMARY KEY,
  triggerdev_run_id        TEXT    NOT NULL UNIQUE,
  triggerdev_task_id       TEXT    NOT NULL,
  triggerdev_status        TEXT    NOT NULL,
  project_id               TEXT    REFERENCES projects(id),
  linked_workflow_event_id TEXT    REFERENCES workflow_events(id),
  linked_agent_run_id      TEXT    REFERENCES agent_runs(id),
  linked_feature_run_id    TEXT    REFERENCES feature_runs(id),
  last_seen_at             TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  version                  INTEGER NOT NULL DEFAULT 1,
  created_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at               TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_triggerdev_runs_task_id ON triggerdev_runs(triggerdev_task_id);
CREATE INDEX idx_triggerdev_runs_project_id ON triggerdev_runs(project_id);

CREATE TABLE merge_gate_evaluations (
  id                          TEXT    PRIMARY KEY,
  feature_run_id              TEXT    NOT NULL REFERENCES feature_runs(id) ON DELETE CASCADE,
  ci_status                   TEXT,
  review_status               TEXT,
  unresolved_blocking_findings INTEGER NOT NULL DEFAULT 0,
  budget_status               TEXT,
  human_approval_required     INTEGER NOT NULL DEFAULT 0,
  human_approval_id           TEXT    REFERENCES human_approvals(id),
  branch_protection_ok        INTEGER NOT NULL DEFAULT 0,
  final_decision              TEXT    NOT NULL,
  evaluated_at                TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  version                     INTEGER NOT NULL DEFAULT 1,
  created_at                  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at                  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX idx_merge_gate_evaluations_feature_run_id ON merge_gate_evaluations(feature_run_id);
