import { z } from 'zod';

// Schema version string included in every outbox/inbox event row.
// Bump this when the payload shape changes; consumers validate against the
// stored version so old rows remain processable.

export const SCHEMA_VERSION = '1.0.0';

// ── Feature execution events ──────────────────────────────────────────────

export const FeatureSelectedPayloadSchema = z.object({
  featureRunId: z.string().uuid(),
  projectId: z.string().uuid(),
  fromState: z.literal('approved_pending_execution'),
  toState: z.literal('selected'),
});
export type FeatureSelectedPayload = z.infer<typeof FeatureSelectedPayloadSchema>;

export const FeatureCodingStartedPayloadSchema = z.object({
  featureRunId: z.string().uuid(),
  projectId: z.string().uuid(),
});
export type FeatureCodingStartedPayload = z.infer<typeof FeatureCodingStartedPayloadSchema>;

export const FeatureCodePushedPayloadSchema = z.object({
  featureRunId: z.string().uuid(),
  projectId: z.string().uuid(),
  commitSha: z.string(),
  branchName: z.string(),
  filesChanged: z.number().int().nonnegative(),
});
export type FeatureCodePushedPayload = z.infer<typeof FeatureCodePushedPayloadSchema>;

export const FeatureCiRunningPayloadSchema = z.object({
  featureRunId: z.string().min(1),
  projectId: z.string().min(1),
  checkRunId: z.string(),
});
export type FeatureCiRunningPayload = z.infer<typeof FeatureCiRunningPayloadSchema>;

export const FeatureCiResultPayloadSchema = z.object({
  featureRunId: z.string().min(1),
  projectId: z.string().min(1),
  checkRunId: z.string(),
  conclusion: z.enum(['success', 'failure', 'cancelled', 'timed_out']),
});
export type FeatureCiResultPayload = z.infer<typeof FeatureCiResultPayloadSchema>;

export const FeatureMergedPayloadSchema = z.object({
  featureRunId: z.string().uuid(),
  projectId: z.string().uuid(),
  mergeSha: z.string(),
});
export type FeatureMergedPayload = z.infer<typeof FeatureMergedPayloadSchema>;

// NOTE (deviation from plan, discovered during HIGH-6 spot-check): featureRunId/projectId here
// use `.string().min(1)`, not `.uuid()`. feature_runs.id/feature_requests.project_id are
// generated by commands/helpers.ts's `generateId()` (`${Date.now()}-${random}`), never a UUID —
// `.uuid()` on these two fields would reject every real payload this handler (and
// RecordChangesRequestedHandler/RecordPrOpenedHandler below) ever emits. This one wasn't in the
// original 11 findings but is the same "payload doesn't match declared schema" class of bug as
// HIGH-6, caught while writing HIGH-6's regression test. `FeatureSelectedPayloadSchema` /
// `FeatureCodingStartedPayloadSchema` / `FeatureCodePushedPayloadSchema` / `FeatureMergedPayloadSchema`
// / `Plan*PayloadSchema` above have the same latent `.uuid()` mismatch but are pre-Phase-7 and
// out of this fix's scope — left untouched here.
export const FeatureHumanRequiredPayloadSchema = z.object({
  featureRunId: z.string().min(1),
  projectId: z.string().min(1),
  reason: z.string(),
});
export type FeatureHumanRequiredPayload = z.infer<typeof FeatureHumanRequiredPayloadSchema>;

// ── Phase 7: GitHub-facing feature execution events ──────────────────────

export const FeaturePrOpenedPayloadSchema = z.object({
  featureRunId: z.string().min(1),
  projectId: z.string().min(1),
  prNumber: z.number().int().positive(),
  branchName: z.string(),
  baseBranch: z.string(),
});
export type FeaturePrOpenedPayload = z.infer<typeof FeaturePrOpenedPayloadSchema>;

export const FeatureChangesRequestedPayloadSchema = z.object({
  featureRunId: z.string().min(1),
  projectId: z.string().min(1),
  reviewId: z.string(),
  reviewer: z.string().nullable(),
});
export type FeatureChangesRequestedPayload = z.infer<typeof FeatureChangesRequestedPayloadSchema>;

// ── Plan events ───────────────────────────────────────────────────────────

export const PlanApprovedPayloadSchema = z.object({
  planId: z.string().uuid(),
  projectId: z.string().uuid(),
});
export type PlanApprovedPayload = z.infer<typeof PlanApprovedPayloadSchema>;

export const PlanActivatedPayloadSchema = z.object({
  planId: z.string().uuid(),
  projectId: z.string().uuid(),
  featureRequestCount: z.number().int().nonnegative(),
});
export type PlanActivatedPayload = z.infer<typeof PlanActivatedPayloadSchema>;

// ── Automation control events ─────────────────────────────────────────────

export const AutomationPausedPayloadSchema = z.object({
  projectId: z.string().uuid(),
  reason: z.enum(['operator', 'budget_exceeded', 'budget_approval_waiting']),
});
export type AutomationPausedPayload = z.infer<typeof AutomationPausedPayloadSchema>;

export const AutomationResumedPayloadSchema = z.object({
  projectId: z.string().uuid(),
});
export type AutomationResumedPayload = z.infer<typeof AutomationResumedPayloadSchema>;

// ── Registry: eventType → schema ─────────────────────────────────────────

export const EVENT_SCHEMAS: Record<string, z.ZodTypeAny> = {
  'feature.selected': FeatureSelectedPayloadSchema,
  'feature.coding_started': FeatureCodingStartedPayloadSchema,
  'feature.code_pushed': FeatureCodePushedPayloadSchema,
  'feature.ci_running': FeatureCiRunningPayloadSchema,
  'feature.ci_passed': FeatureCiResultPayloadSchema,
  'feature.ci_failed': FeatureCiResultPayloadSchema,
  'feature.merged': FeatureMergedPayloadSchema,
  'feature.human_required': FeatureHumanRequiredPayloadSchema,
  'feature.pr_opened': FeaturePrOpenedPayloadSchema,
  'feature.changes_requested': FeatureChangesRequestedPayloadSchema,
  'plan.approved': PlanApprovedPayloadSchema,
  'plan.activated': PlanActivatedPayloadSchema,
  'automation.paused_by_operator': AutomationPausedPayloadSchema,
  'automation.budget_exceeded': AutomationPausedPayloadSchema,
  'automation.resumed': AutomationResumedPayloadSchema,
};

export function validateEventPayload(eventType: string, payload: unknown): void {
  const schema = EVENT_SCHEMAS[eventType];
  if (schema) {
    schema.parse(payload);
  }
}
