import type {
  PlannerAgentAdapter,
  PlannerBehavior,
  PlannerInput,
  PlannerOutput,
  PlanSectionGenerationInput,
  PlanSectionGenerationOutput,
  FeatureBacklogGenerationInput,
  FeatureBacklogGenerationOutput,
  AdapterCall,
} from './types.js';

export class MockPlannerAdapter implements PlannerAgentAdapter {
  readonly role = 'PlannerAgentAdapter' as const;
  readonly calls: AdapterCall<PlannerInput, PlannerOutput>[] = [];

  constructor(public behavior: PlannerBehavior = 'sufficient') {}

  async run(input: PlannerInput): Promise<PlannerOutput> {
    let output: PlannerOutput;

    switch (this.behavior) {
      case 'sufficient':
        output = {
          readinessResult: 'sufficient',
          questions: [],
          assumptions: [],
          gaps: [],
        };
        break;

      case 'sufficient_with_assumptions':
        output = {
          readinessResult: 'sufficient_with_assumptions',
          questions: [],
          assumptions: [
            {
              description: 'Assuming standard REST API patterns apply',
              confidence: 'high',
            },
            {
              description: 'Assuming PostgreSQL is the production database',
              confidence: 'medium',
            },
          ],
          gaps: [],
        };
        break;

      case 'insufficient':
        output = {
          readinessResult: 'insufficient',
          questions: [
            { question: 'What is the expected user volume?', round: 1 },
            { question: 'What authentication method should be used?', round: 1 },
          ],
          assumptions: [],
          gaps: [
            {
              description: 'Missing non-functional requirements (performance, scalability)',
              severity: 'blocking',
            },
          ],
        };
        break;
    }

    this.calls.push({ input, output, calledAt: new Date().toISOString() });
    return output;
  }

  async generatePlanSections(
    input: PlanSectionGenerationInput,
  ): Promise<PlanSectionGenerationOutput> {
    return {
      title: 'Mock Implementation Plan',
      summary: 'Generated by MockPlannerAdapter for test scenarios.',
      sections: [
        { title: 'Overview', content: `Plan derived from: ${input.specificationContent}` },
      ],
    };
  }

  async generateFeatureBacklog(
    input: FeatureBacklogGenerationInput,
  ): Promise<FeatureBacklogGenerationOutput> {
    return {
      features: input.planSections.map((section, index) => ({
        frId: `FR-${String(index + 1).padStart(3, '0')}`,
        title: section.title,
        description: section.content,
        kind: 'feature' as const,
        priority: index,
        dependsOnFrIds: [],
        acceptanceCriteria: ['Meets the described requirement.'],
        testExpectations: [{ description: 'Covered by unit tests.', testType: 'unit' as const }],
      })),
    };
  }
}
